### PR TITLE
angular 13 update

### PR DESCRIPTION
**Pull request by dereekb**

### CODE REVIEW

**Comment by schulzi66** [comment]
Hey @dereekb,
thanks for updating ng-overlay-container to angular 13! Much appreciated! 
I was just wondering if there will be more commits comming in this PR because you are working on the angular-13-dist branch?

As soon as you are done I will test everything and give it a go. 
Also would you mind updating the README.md to match the new versions?

**Comment by schulzi66** [comment]
@dereekb Ok perfect. I will give it a test and also approve and release as soon the Readme is updated 👍

**Comment by schulzi66** [comment]
Also feel free to include yourself as a contributor in the package.json if you like

**Comment by schulzi66** [comment]
Thanks for updating the README.md. For some reasons the pipeline does not want to use the latest version of the .yml file. I will check it and merge your PR

**Comment by dereekb** [comment]
@schulzi66 forgot to change the peer dependencies on the actual package, so I fixed that and added contributors. I've been using Nx.dev so I usually only change the root package!

Should be good to go now.

**Comment by schulzi66** [comment]
@dereekb Perfect. Yes thought about migrating to nx just for the auto update of the package.json. I will merge it now. Thanks for the contribution! 💪

**Pull request merged**
